---
apiVersion: v1
kind: Secret
metadata:
  name: dkerov-dkerov-poi-map-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23Janus2/dkerov-frontend-gitops
